stages:
  - setup
  - build
  - deploy

default:
  image: mercy-u:5050/mercy/ci-cd-runners/docfx:10.0
  before_script:
    - node --version
    - npm --version
    - dotnet --version

build_site:
  stage: build
  script:
    - docfx docfx.json
  artifacts:
    paths:
      - _site/
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - when: never

pages:
  stage: deploy
  needs:
    - job: build_site
      artifacts: true
  script:
    - mkdir -p public
    - cp -r _site/. public/
  pages:
    publish: public/
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
